services:
  servidor-frontend:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./temp:/usr/src/app/temp
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-01-18T00-31-37Z-cpuv1
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
