services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./temp:/usr/src/app/temp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
